djangoWeb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [

    path('', include('mysite.urls')),
    path('ysy/', admin.site.urls),
    # path('about', include('mysite.urls')),
path(r'^tinymce/', include('tinymce.urls')),
]

mysite/urls.py
from django.urls import path

from . import views
app_name = 'mysite'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('<nId>', views.detail, name='detail'),
]

tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)
from django.urls import path
from . import views
app_name = 'tinymce'
urlpatterns = [
    path(r'^js/textareas/(?P<name>.+)/$', views.textareas_js, name='tinymce-js'),
    path(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', views.textareas_js, name='tinymce-js-lang'),
    path(r'^spellchecker/$', views.spell_check),
    path(r'^flatpages_link_list/$', views.flatpages_link_list),
    path(r'^compressor/$', views.compressor, name='tinymce-compressor'),
    path(r'filebrowser/', views.filebrowser, name='tinymce-filebrowser'),
    path(r'^preview/(?P<name>.+)/$', views.preview, name='tinymce-preview'),
]

mysite/models.py
from django.db import models
from tinymce.models import HTMLField


class Note(models.Model):
    Categorys = (
        ('l', '生活'),
        ('t', '技术'),
        ('e', '经济'),
    )
    nId = models.CharField(verbose_name='id',max_length=100,primary_key=True)
    nPicUrl= models.CharField(verbose_name='图片', max_length=100,null=True,blank=True)
    nTitle = models.CharField(verbose_name='标题',max_length=100)
    nSummary = models.CharField(verbose_name='摘要', max_length=100,null=True,blank=True)
    nContent = HTMLField('正文')
    nCategory = models.CharField(verbose_name='分类', max_length=1, choices=Categorys)
    nTag = models.TextField(verbose_name='标签',max_length=50,null=True,blank=True)
    nCreateTime = models.DateTimeField(verbose_name='创建时间')
    nUpdateTime = models.DateTimeField(verbose_name='更新时间')
    nView = models.IntegerField(verbose_name='阅读量',default=0)
    nLike = models.IntegerField(verbose_name='点赞量',default=0)
    nIsDeleted = models.BooleanField(verbose_name='已删除',default=False)
    nIsPublic = models.BooleanField(verbose_name='公开可见',default=False)

tinymce/models.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

from django.db import models
from django.contrib.admin import widgets as admin_widgets
from tinymce import widgets as tinymce_widgets
try:
    from south.modelsinspector import add_introspection_rules
    add_introspection_rules([], ['^tinymce\.models\.HTMLField'])
except ImportError:
    pass

class HTMLField(models.TextField):
    """
    A large string field for HTML content. It uses the TinyMCE widget in
    forms.
    """
    def __init__(self, *args, **kwargs):
        self.tinymce_profile = kwargs.pop('profile', None)
        super(HTMLField, self).__init__(*args, **kwargs)

    def formfield(self, **kwargs):
        defaults = {
            'widget': tinymce_widgets.TinyMCE(profile=self.tinymce_profile)
        }
        defaults.update(kwargs)

        # As an ugly hack, we override the admin widget
        if defaults['widget'] == admin_widgets.AdminTextareaWidget:
            defaults['widget'] = tinymce_widgets.AdminTinyMCE()

        return super(HTMLField, self).formfield(**defaults)

mysite/views.py
from django.shortcuts import get_object_or_404,render
from mysite.models import Note
# Create your views here.


def index(request,category=''):
    if category == '':
        nList = Note.objects.filter(nIsPublic=True).order_by('-nUpdateTime')
    elif category == 'pri':
        nList = Note.objects.filter(nIsPublic=False).order_by('-nUpdateTime')
    else:
        nList = Note.objects.filter(nCategory=category,nIsPublic=True).order_by('-nUpdateTime')
    return render(request, 'mysite/index.html', {'nList': nList,'category': category, 'isIndex': ''})


def detail(request,nId):
    note = get_object_or_404(Note, pk=nId)
    note.nView += 1
    note.save()
    return render(request,'mysite/detail.html',{'note':note,'isIndex':'wrap_detail'})


def about(request):
    return render(request, 'mysite/about.html')

tinymce/views.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

import logging
from django.urls import reverse
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.template import RequestContext, loader
import simplejson
from django.utils.translation import ugettext as _
from tinymce.compressor import gzip_compressor
from tinymce.widgets import get_language_config
try:
    from django.views.decorators.csrf import csrf_exempt
except ImportError:
    pass

def textareas_js(request, name, lang=None):
    """
    Returns a HttpResponse whose content is a Javscript file. The template
    is loaded from 'tinymce/<name>_textareas.js' or
    '<name>/tinymce_textareas.js'. Optionally, the lang argument sets the
    content language.
    """
    template_files = (
        'tinymce/%s_textareas.js' % name,
        '%s/tinymce_textareas.js' % name,
    )
    template = loader.select_template(template_files)

    vars = get_language_config(lang)
    vars['content_language'] = lang
    context = RequestContext(request, vars)

    return HttpResponse(template.render(context),
            content_type="application/x-javascript")

def spell_check(request):
    """
    Returns a HttpResponse that implements the TinyMCE spellchecker protocol.
    """
    try:
        import enchant

        raw = request.raw_post_data
        input = simplejson.loads(raw)
        id = input['id']
        method = input['method']
        params = input['params']
        lang = params[0]
        arg = params[1]

        if not enchant.dict_exists(str(lang)):
            raise RuntimeError("dictionary not found for language '%s'" % lang)

        checker = enchant.Dict(str(lang))

        if method == 'checkWords':
            result = [word for word in arg if word and not checker.check(word)]
        elif method == 'getSuggestions':
            result = checker.suggest(arg)
        else:
            raise RuntimeError("Unkown spellcheck method: '%s'" % method)
        output = {
            'id': id,
            'result': result,
            'error': None,
        }
    except Exception:
        logging.exception("Error running spellchecker")
        return HttpResponse(_("Error running spellchecker"))
    return HttpResponse(simplejson.dumps(output),
            content_type='application/json')

try:
    spell_check = csrf_exempt(spell_check)
except NameError:
    pass

def preview(request, name):
    """
    Returns a HttpResponse whose content is an HTML file that is used
    by the TinyMCE preview plugin. The template is loaded from
    'tinymce/<name>_preview.html' or '<name>/tinymce_preview.html'.
    """
    template_files = (
        'tinymce/%s_preview.html' % name,
        '%s/tinymce_preview.html' % name,
    )
    template = loader.select_template(template_files)
    return HttpResponse(template.render(RequestContext(request)),
            content_type="text/html")


def flatpages_link_list(request):
    """
    Returns a HttpResponse whose content is a Javscript file representing a
    list of links to flatpages.
    """
    from django.contrib.flatpages.models import FlatPage
    link_list = [(page.title, page.url) for page in FlatPage.objects.all()]
    return render_to_link_list(link_list)


def compressor(request):
    """
    Returns a GZip-compressed response.
    """
    return gzip_compressor(request)


def render_to_link_list(link_list):
    """
    Returns a HttpResponse whose content is a Javscript file representing a
    list of links suitable for use wit the TinyMCE external_link_list_url
    configuration option. The link_list parameter must be a list of 2-tuples.
    """
    return render_to_js_vardef('tinyMCELinkList', link_list)

def render_to_image_list(image_list):
    """
    Returns a HttpResponse whose content is a Javscript file representing a
    list of images suitable for use wit the TinyMCE external_image_list_url
    configuration option. The image_list parameter must be a list of 2-tuples.
    """
    return render_to_js_vardef('tinyMCEImageList', image_list)

def render_to_js_vardef(var_name, var_value):
    output = "var %s = %s" % (var_name, simplejson.dumps(var_value))
    return HttpResponse(output, content_type='application/x-javascript')

def filebrowser(request):
    try:
        fb_url = request.build_absolute_uri(reverse('fb_browse'))
    except:
        fb_url = request.build_absolute_uri(reverse('filebrowser:fb_browse'))

    return render_to_response('tinymce/filebrowser.js', {'fb_url': fb_url},
            context_instance=RequestContext(request))

mysite/templates/mysite/about.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="keywords" content="冥想,编程,外语,金融,人工智能">
      <meta name="description" content="分享一个冥想练习多年和互联网从业者的市面上罕见的生活经验和习惯，帮有缘人更加幸福健康地成长。">
      <meta name="author" content="">
      <title>何以愚-一个让你轻松成长的地方</title>
{% load static %}
      <link rel="icon" href="{% static 'mysite/img/redmoon.ico' %}" type="image/x-icon" />
    <link rel="shortcut icon" href="{% static 'mysite/img/redmoon.ico' %}" type="image/x-icon" />
    <!-- Bootstrap core CSS -->
     <link href="{% static 'mysite/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'mysite/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'mysite/css/clean-blog.min.css' %}" rel="stylesheet">
	<style>
	.mx-auto h4{font-weight: 700;}
	.mx-auto p{font-size:1rem;}
	</style>
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?e1fd6a690a98a8c65e9647260a2df3e1";
  var s = document.getElementsByTagName("script")[0];
  s.parentNode.insertBefore(hm, s);
})();
</script>

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="/">何以愚</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          导航
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">首页</a>
            </li>
{#            <li class="nav-item">#}
{#              <a class="nav-link" href="life.html">生活</a>#}
{#            </li>#}
{#            <li class="nav-item">#}
{#              <a class="nav-link" href="think.html">思维</a>#}
{#            </li>#}
{#			<li class="nav-item">#}
{#              <a class="nav-link" href="hobby.html">兴趣</a>#}
{#            </li>#}
            <li class="nav-item">
              <a class="nav-link" href="/about/">关于我</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url({% static 'mysite/img/8.jpg' %})">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-8 mx-auto">
            <div class="page-heading">
              <!-- <h1>About Me</h1>-->
              <span class="subheading">别管我是谁！</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-8 mx-auto">

            <p>用身心透支的方式努力奋斗的人太多，极少人知道身心安宁、健康的方式才是最高效、最持久的奋斗法宝，更极少人知道怎么获得这种能力。</p>


            <p>社会上打拼的我们，都是几十亿中非常普通的个体，深深体验社会丛林的艰辛和困扰，有时感慨自身的微弱。</p>


            <p>但这是现实，为啥我们不身心放松些，看透些思想，发现有趣的事情，过好仅有一次的人生呢？</p>

        </div>
      </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
{#            <ul class="list-inline text-center">#}
{#              <li class="list-inline-item">#}
{#                <a href="#">#}
{#                  <span class="fa-stack fa-lg">#}
{#                    <i class="fas fa-circle fa-stack-2x"></i>#}
{#                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>#}
{#                  </span>#}
{#                </a>#}
{#              </li>#}
{#              <li class="list-inline-item">#}
{#                <a href="#">#}
{#                  <span class="fa-stack fa-lg">#}
{#                    <i class="fas fa-circle fa-stack-2x"></i>#}
{#                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>#}
{#                  </span>#}
{#                </a>#}
{#              </li>#}
{#              <li class="list-inline-item">#}
{#                <a href="#">#}
{#                  <span class="fa-stack fa-lg">#}
{#                    <i class="fas fa-circle fa-stack-2x"></i>#}
{#                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>#}
{#                  </span>#}
{#                </a>#}
{#              </li>#}
{#            </ul>#}
            <p class="copyright text-muted" style="font-size: 14px;">© 何以愚 2018-2019 粤ICP备18097511号</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'mysite/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'mysite/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'mysite/js/clean-blog.min.js' %}"></script>

  </body>

</html>

mysite/templates/mysite/index.html
<!DOCTYPE html>
<html>

<head>
    <title>Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
{#    {% load static %}#}
{#    <link rel="stylesheet" href="{% static 'mysite/css/uikit.min.css' %}" />#}
{#    <link rel="stylesheet" href="{% static 'mysite/css/theme.css' %}" />#}
{#    <script src="{% static 'mysite/js/uikit.min.js' %}"></script>#}
{#    <script src="{% static 'mysite/js/uikit-icons.min.js' %}" ></script>#}
    <link rel="stylesheet" href="https://langlicun.com/static/mysite/css/uikit.min.css"/>
    <link href="https://langlicun.com/static/mysite/css/theme.css" rel="stylesheet">
    <script src="https://langlicun.com/static/mysite/js/uikit.min.js"></script>
    <script src="https://langlicun.com/static/mysite/js/uikit-icons.min.js"></script>
    <style>
        .uk-navbar-nav > li > a {
            color: #ffffff;
            font-weight: 400;
        }

        .uk-navbar-nav-title > li > a {
            color: #fff;
            font-size: 22px;
        }

        .uk-navbar-nav > li > a:hover {
            color: #ffffff;
            font-weight: bold;
        }

        .uk-margin-remove-top > li {
            margin-top: 10px;
        }

        .container:hover .cu_toolbar {
            display: block;
        }
    </style>
    <script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?e1fd6a690a98a8c65e9647260a2df3e1";
  var s = document.getElementsByTagName("script")[0];
  s.parentNode.insertBefore(hm, s);
})();
</script>
</head>

<body>
<nav style="z-index: 100;height: 60px;" uk-navbar>

    <div class="uk-navbar-left">
        <ul class="uk-navbar-nav uk-navbar-nav-title">
            <li>
                <a href="index.html"><img src="https://langlicun.com/static/mysite/img/bangbangtang.svg" width="40" height="40" uk-svg>abc</a>
            </li>

        </ul>

    </div>

    <div class="uk-navbar-right">

        {#            <ul class="uk-navbar-nav">#}
        {##}
        {#                <li class="uk-parent"><a href="course.html" aria-expanded="false" class="">To语言教程</a>#}
        {#                </li>#}
        {#                <li class="uk-parent"><a href="course.html" aria-expanded="false" class="">知乎高级教程</a>#}
        {#                </li>#}
        {#                <li class="uk-parent"><a href="course.html" aria-expanded="false" class="">做菜入门教程</a>#}
        {#                </li>#}
        {#                <li class="uk-parent"><a href="course.html" aria-expanded="false" class="">穿衣搭配指南</a>#}
        {#                </li>#}
        {#                <li class="uk-parent"><a href="course.html" aria-expanded="false" class="">身心健康训练营</a>#}
        {#                </li>#}
        {#                <li class="uk-parent new-uk-active"><a href="blog.html" aria-expanded="false" class="">愚文</a>#}
        {#                </li>#}
        {#            </ul>#}

    </div>

</nav>

<!-- <div class="uk-background-fixed uk-background-center-center uk-height-medium uk-width-1-1 uk-position-top" style="background-image: url(../image/210546.png);"></div>    -->
<div class="uk-background-image@m uk-background-cover uk-background-muted uk-flex uk-flex-center uk-flex-middle uk-position-top"
     style="height: 360px; background-image: url('https://langlicun.com/static/mysite/img/210546.png');">
    <p class="uk-h4 uk-margin-remove uk-visible@m blog-uk-light">一个让你轻松成长的地方</p>
    <p class="uk-h4 uk-margin-remove uk-hidden@m">Image not shown</p>
</div>
<!--正文-->

<div class="uk-section uk-section-default" style="margin-top:360px;">
    <div class="uk-container uk-container-large">
        <div class="uk-grid-divider uk-child-width-expand@s" uk-grid>

            <div class="uk-width-4-5@m" uk-grid>

                <div class="uk-width-3-4@m">


                    {% for n in nList %}


                        <div class="uk-flex-middle" uk-grid>
                            <div class="uk-width-4-5@m">
                                <h4 onclick="window.open('{% url 'mysite:detail' n.nId %}')" class="index-article-list-title">{{ n.nTitle }}</h4>
                                <p>{{ n.nSummary }}</p>
                                <p><span class="uk-margin-small-right" uk-icon="pencil"></span><span
                                        class="uk-text-middle">{{ n.nCreateTime }}</span><span
                                        class="uk-margin-small-right uk-margin-small-left"
                                        uk-icon="heart"></span> <span class="uk-text-middle">{{ n.nView }}</span></p>
                            </div>
                            <div class="uk-width-1-5@m uk-flex-first uk-animation-toggle ">
                                {% if n.nPicUrl != none %}
                                    <img class="img-border-radius" src="{{ n.nPicUrl }}" class="uk-animation-slide-left">
                                {% endif %}

                            </div>
                        </div>


                    {% endfor %}

                </div>
                <div class="uk-width-1-5@m uk-flex-first"></div>
            </div>
            <div>
                <article class="uk-comment">
                    <header class="uk-comment-header uk-grid-medium uk-flex-middle" uk-grid>
                        <div class="uk-width-auto">
                            <img class="uk-border-pill" src="https://langlicun.com/static/mysite/img/avatar.jpg" width="80" height="80" alt="">
                        </div>
                        <div class="uk-width-expand">
                            <h4 class="uk-comment-title uk-margin-remove"><a class="uk-link-reset" href="#">何以愚</a>
                            </h4>
                            <ul class="uk-comment-meta uk-subnav uk-margin-remove-top">
                                <li><a href="#">射手座</a></li>
                                <li><a href="#">程序员-冥想练习生</a></li>

                            </ul>
                        </div>
                    </header>
                    <div class="uk-comment-body">
                        <p class="container">现在用身心透支的方式努力奋斗的人太多，极少人知道身心安宁、健康的方式才是最高效、最持久的奋斗法宝，更极少人知道怎么获得这种能力。物以稀为贵。
                        </p>
                    </div>
                    <div style="margin-top: 10px;">

                        <a href="https://www.zhihu.com/people/shi-cuo-92-50/answers?order_by=created"
                           target="_blank"><img src="https://langlicun.com/static/mysite/img/zhihu.svg" width="30" height="30" uk-svg> 来啊，来追我啊</a>
{#                        <div class="uk-inline">#}
{#                            <a><img src="https://langlicun.com/static/mysite/img/wechat.svg" width="30" height="30"#}
{#                                    uk-svg></a>#}
{#                            <div class="cu_toolbar" style="display: none;" uk-drop="pos: bottom-center"><img#}
{#                                    src="https://langlicun.com/static/mysite/img/avatar.jpg"></div>#}
{#                        </div>#}
{#                        <a href="https://github.com/heyiyu" target="_blank" uk-icon="github" width="30" height="30"></a>#}
                    </div>


                </article>
            </div>
        </div>
    </div>
</div>
</body>

</html>

mysite/templates/mysite/index2.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="keywords" content="冥想,编程,外语,金融,人工智能">
    <meta name="description" content="分享一个冥想练习多年和互联网从业者的市面上罕见的生活经验和习惯，帮有缘人更加幸福健康地成长。">
    <meta name="author" content="">

    <title>何以愚-一个让你轻松成长的地方</title>
{% load static %}
      <link rel="icon" href="{% static 'mysite/img/redmoon.ico' %}" type="image/x-icon" />
    <link rel="shortcut icon" href="{% static 'mysite/img/redmoon.ico' %}" type="image/x-icon" />
    <!-- Bootstrap core CSS -->
    <link href="{% static 'mysite/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'mysite/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'mysite/css/clean-blog.min.css' %}" rel="stylesheet">
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?e1fd6a690a98a8c65e9647260a2df3e1";
  var s = document.getElementsByTagName("script")[0];
  s.parentNode.insertBefore(hm, s);
})();
</script>

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="/"></a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          导航
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">首页</a>
            </li>
{#            <li class="nav-item">#}
{#              <a class="nav-link" href="life.html">生活</a>#}
{#            </li>#}
{#            <li class="nav-item">#}
{#              <a class="nav-link" href="think.html">思维</a>#}
{#            </li>#}
{#			<li class="nav-item">#}
{#              <a class="nav-link" href="hobby.html">兴趣</a>#}
{#            </li>#}
            <li class="nav-item">
              <a class="nav-link" href="/about/">关于我</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url({% static 'mysite/img/surf.jpg' %})">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <!--<h1>你好！</h1>-->
              <span class="subheading">一个让你轻松成长的地方</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% for n in nList  %}
			<div class="row">
				<div class="post-preview col-lg-9 col-md-10 mx-auto">
					<a href="{% url 'mysite:detail' n.nId %}">
					  <h3 class="post-title">
						{{ n.nTitle }}
					  </h3>
					</a>
					<p class="post-meta">{{ n.nCreateTime }} &nbsp;&nbsp;&nbsp; 阅读 {{ n.nView }}</p>
				</div>
				<div class="col-lg-3 col-md-2 mx-auto">
                    {% if n.nPicUrl != '' and n.nPicUrl != null %}
				 <img style="display: block;width: 100%;height: 100%;vertical-align: top;" src="https://langlicun.com/static/mysite/img/{{ n.nPicUrl }}">
				{% endif %}
                </div>
			</div>
                {% if forloop.counter < nList.count %}
                    <hr>
                {% endif %}

            {% endfor %}
      </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
{#            <ul class="list-inline text-center">#}
{#              <li class="list-inline-item">#}
{#                <a href="#">#}
{#                  <span class="fa-stack fa-lg">#}
{#                    <i class="fas fa-circle fa-stack-2x"></i>#}
{#                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>#}
{#                  </span>#}
{#                </a>#}
{#              </li>#}
{#              <li class="list-inline-item">#}
{#                <a href="#">#}
{#                  <span class="fa-stack fa-lg">#}
{#                    <i class="fas fa-circle fa-stack-2x"></i>#}
{#                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>#}
{#                  </span>#}
{#                </a>#}
{#              </li>#}
{#              <li class="list-inline-item">#}
{#                <a href="#">#}
{#                  <span class="fa-stack fa-lg">#}
{#                    <i class="fas fa-circle fa-stack-2x"></i>#}
{#                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>#}
{#                  </span>#}
{#                </a>#}
{#              </li>#}
{#            </ul>#}
            <p class="copyright text-muted">&copy; 何以愚 2018-2019 粤ICP备18097511号</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'mysite/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'mysite/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'mysite/js/clean-blog.min.js' %}"></script>

  </body>

</html>